/*
 * clap entry
 *
 * This uses extern versions of the entry methods from a static library to create
 * a working exported C linkage clap entry point
 */

#include "rust_plugin_1_clap_entry.h"

// Generated by cbindgen from Rust code
#include "rust-plugin-1-bindings.h"

extern "C"
{
#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wattributes"  // other peoples errors are outside my scope
#endif

CLAP_EXPORT extern const rust_ffi::clap_plugin_entry clap_entry;
const CLAP_EXPORT struct rust_ffi::clap_plugin_entry clap_entry = rust_ffi::rust_clap_entry;

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif
}
